### ISSUE TITLE
stackdriver-prometheus vs prometheus-to-sd

### ISSUE THREAD

**Issue by geekflyer** [Stackdriver/stackdriver-prometheus#15]
Hi,

I'm a bit confused as to how stackdriver-prometheus relates to prometheus-to-sd and what are the pros / cons of using each? What is the recommended option way of sending prometheus-like metrics to stackdriver? 

Both projects are maintained by Google which doesn't make the choice easier :)
I hope someone can clarify, perhaps adding a note to the README would be useful for others.

**Comment by geekflyer** [comment]
Hi @jkohen thanks for your prompt answer. Unfortunately I'm still not 100% clear what I should use in our scenario. I should have probably clarified this before, but here's a bit more context:

- we run GKE
- we aim to monitor k8s state metrics like "replicas_available" for our own k8s apps that run on gke
- we would run stackdriver-prometheus or prometheus-to-sd both in gke / k8s
- we don't aim to use prometheus directly (i.e. no query), but rather make use of one those packages only to be able to scrape metrics which are only exported in prometheus format (e.g. kube-state-metrics).

**Comment by jkohen** [comment]
@geekflyer I believe stackdriver-prometheus will meet your needs, and it's what I would recommend. If that's not the case, I'd like to hear more about your needs.
