### ISSUE TITLE
Best way to drop default Prometheus metrics

### ISSUE THREAD

**Issue by shaobos** [Stackdriver/stackdriver-prometheus#20]
Hi,

We recently adopted Stackdriver Kubernetes Monitoring: https://cloud.google.com/monitoring/api/metrics_other#prometheus. The default Prometheus manifest file is used with slight modification in our cluster: https://github.com/Stackdriver/stackdriver-prometheus/blob/master/documentation/examples/prometheus-service.yml

We defined a couple of Counters and Histograms to monitor our services. The metrics look good in Stackdriver. After a couple of weeks we started noticing a high usage of Stackdriver Monitoring and I suspect it has something to do with the additional external metrics coming out of the box. Just to name a few of them:

* external.googleapis.com/prometheus/kubelet_network_plugin_operations_latency_microseconds
* external.googleapis.com/prometheus/prometheus_remote_storage_succeeded_samples_total
* external.googleapis.com/prometheus/prometheus_sd_dns_lookup_failures_total
* external.googleapis.com/prometheus/prometheus_target_sync_length_seconds_sum

Can someone suggest whether they're essential for Kubernetes Monitoring? Also would be great to know the best way to drop them if possible. 

I found this question more relevant here than Prometheus user group as it involves GKE and Stackdriver.

Thanks

**Comment by jkohen** [comment]
@shaobos This is a good place to ask that question. Running Prometheus is optional for the Kubernetes Monitoring experience in Google Cloud, so all the metrics you listed are optional.

You can drop metrics using standard Prometheus Server features. In this case you have a couple options:
- add an instance of `write_relabel_configs` under `remote_write`: https://prometheus.io/docs/prometheus/2.2/configuration/configuration/#%3Cremote_write%3E
- add an instance of `relabel_configs` under the appropriate `scrape_config` (probably `kubernetes-pods-containers`, `kubernetes-service-endpoints`, or both): https://prometheus.io/docs/prometheus/2.2/configuration/configuration/#%3Cscrape_config%3E

I hope that helps.

**Comment by shaobos** [comment]
thanks @jkohen, it works like a charm. I deployed the change based on your suggestion 2 days ago and the cost from yesterday went down roughly 95%! Really appreciate your pointers.
